# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Dec 14 17:32:44 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 555)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.BHTab = QtGui.QWidget()
        self.BHTab.setObjectName("BHTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.BHTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = Show3D(self.BHTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtGui.QListWidget(self.BHTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.btnRun = QtGui.QPushButton(self.BHTab)
        self.btnRun.setObjectName("btnRun")
        self.verticalLayout_3.addWidget(self.btnRun)
        self.btnPause = QtGui.QPushButton(self.BHTab)
        self.btnPause.setObjectName("btnPause")
        self.verticalLayout_3.addWidget(self.btnPause)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.BHTab, "")
        self.NEBTab = QtGui.QWidget()
        self.NEBTab.setObjectName("NEBTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.NEBTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.oglPath = Show3D(self.NEBTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oglPath.sizePolicy().hasHeightForWidth())
        self.oglPath.setSizePolicy(sizePolicy)
        self.oglPath.setObjectName("oglPath")
        self.gridLayout_4.addWidget(self.oglPath, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listMinima1 = QtGui.QListWidget(self.NEBTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listMinima1.sizePolicy().hasHeightForWidth())
        self.listMinima1.setSizePolicy(sizePolicy)
        self.listMinima1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listMinima1.setObjectName("listMinima1")
        self.verticalLayout_5.addWidget(self.listMinima1)
        self.listMinima2 = QtGui.QListWidget(self.NEBTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listMinima2.sizePolicy().hasHeightForWidth())
        self.listMinima2.setSizePolicy(sizePolicy)
        self.listMinima2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listMinima2.setObjectName("listMinima2")
        self.verticalLayout_5.addWidget(self.listMinima2)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        self.sliderFrame = QtGui.QSlider(self.NEBTab)
        self.sliderFrame.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFrame.setObjectName("sliderFrame")
        self.gridLayout_4.addWidget(self.sliderFrame, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(20, 0, 20, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnAlign = QtGui.QPushButton(self.NEBTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlign.sizePolicy().hasHeightForWidth())
        self.btnAlign.setSizePolicy(sizePolicy)
        self.btnAlign.setMaximumSize(QtCore.QSize(100, 100))
        self.btnAlign.setObjectName("btnAlign")
        self.gridLayout_2.addWidget(self.btnAlign, 1, 0, 1, 1)
        self.btnEnergies = QtGui.QPushButton(self.NEBTab)
        self.btnEnergies.setObjectName("btnEnergies")
        self.gridLayout_2.addWidget(self.btnEnergies, 2, 0, 1, 1)
        self.btnNEB = QtGui.QPushButton(self.NEBTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNEB.sizePolicy().hasHeightForWidth())
        self.btnNEB.setSizePolicy(sizePolicy)
        self.btnNEB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnNEB.setObjectName("btnNEB")
        self.gridLayout_2.addWidget(self.btnNEB, 2, 1, 1, 1)
        self.btnInvert = QtGui.QPushButton(self.NEBTab)
        self.btnInvert.setObjectName("btnInvert")
        self.gridLayout_2.addWidget(self.btnInvert, 1, 1, 1, 1)
        self.btnConnect = QtGui.QPushButton(self.NEBTab)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_2.addWidget(self.btnConnect, 3, 0, 1, 1)
        self.btnDisconnectivity_graph = QtGui.QPushButton(self.NEBTab)
        self.btnDisconnectivity_graph.setObjectName("btnDisconnectivity_graph")
        self.gridLayout_2.addWidget(self.btnDisconnectivity_graph, 5, 0, 1, 2)
        self.btnShowGraph = QtGui.QPushButton(self.NEBTab)
        self.btnShowGraph.setObjectName("btnShowGraph")
        self.gridLayout_2.addWidget(self.btnShowGraph, 4, 0, 1, 1)
        self.btnReconnect = QtGui.QPushButton(self.NEBTab)
        self.btnReconnect.setObjectName("btnReconnect")
        self.gridLayout_2.addWidget(self.btnReconnect, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 3, 1, 1)
        self.tabWidget.addTab(self.NEBTab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.sliderTS = QtGui.QSlider(self.tab)
        self.sliderTS.setMaximum(2)
        self.sliderTS.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTS.setObjectName("sliderTS")
        self.gridLayout_8.addWidget(self.sliderTS, 1, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(20, 0, 20, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnTSSearch = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTSSearch.sizePolicy().hasHeightForWidth())
        self.btnTSSearch.setSizePolicy(sizePolicy)
        self.btnTSSearch.setMaximumSize(QtCore.QSize(100, 100))
        self.btnTSSearch.setObjectName("btnTSSearch")
        self.gridLayout_6.addWidget(self.btnTSSearch, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 1, 2, 1, 1)
        self.oglTS = Show3D(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oglTS.sizePolicy().hasHeightForWidth())
        self.oglTS.setSizePolicy(sizePolicy)
        self.oglTS.setObjectName("oglTS")
        self.gridLayout_8.addWidget(self.oglTS, 0, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.listFrom = QtGui.QListWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFrom.sizePolicy().hasHeightForWidth())
        self.listFrom.setSizePolicy(sizePolicy)
        self.listFrom.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listFrom.setObjectName("listFrom")
        self.verticalLayout_9.addWidget(self.listFrom)
        self.listTo = QtGui.QListWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listTo.sizePolicy().hasHeightForWidth())
        self.listTo.setSizePolicy(sizePolicy)
        self.listTo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listTo.setObjectName("listTo")
        self.verticalLayout_9.addWidget(self.listTo)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 25))
        self.menubar.setObjectName("menubar")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDelete_Minimum = QtGui.QAction(MainWindow)
        self.actionDelete_Minimum.setObjectName("actionDelete_Minimum")
        self.actionEditParams = QtGui.QAction(MainWindow)
        self.actionEditParams.setObjectName("actionEditParams")
        self.menuSimulation.addAction(self.actionConnect)
        self.menuHelp.addAction(self.actionAbout)
        self.menuActions.addAction(self.actionDelete_Minimum)
        self.menuActions.addAction(self.actionEditParams)
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("currentItemChanged(QListWidgetItem*,QListWidgetItem*)"), MainWindow.SelectMinimum)
        QtCore.QObject.connect(self.btnRun, QtCore.SIGNAL("clicked()"), MainWindow.StartBasinHopping)
        QtCore.QObject.connect(self.btnAlign, QtCore.SIGNAL("clicked()"), MainWindow.AlignMinima)
        QtCore.QObject.connect(self.btnNEB, QtCore.SIGNAL("clicked()"), MainWindow.ConnectMinima)
        QtCore.QObject.connect(self.listMinima1, QtCore.SIGNAL("currentItemChanged(QListWidgetItem*,QListWidgetItem*)"), MainWindow.SelectMinimum1)
        QtCore.QObject.connect(self.listMinima2, QtCore.SIGNAL("currentItemChanged(QListWidgetItem*,QListWidgetItem*)"), MainWindow.SelectMinimum2)
        QtCore.QObject.connect(self.sliderFrame, QtCore.SIGNAL("sliderMoved(int)"), MainWindow.showFrame)
        QtCore.QObject.connect(self.btnEnergies, QtCore.SIGNAL("pressed()"), MainWindow.showEnergies)
        QtCore.QObject.connect(self.actionConnect, QtCore.SIGNAL("activated()"), MainWindow.connect)
        QtCore.QObject.connect(self.listFrom, QtCore.SIGNAL("currentItemChanged(QListWidgetItem*,QListWidgetItem*)"), MainWindow.SelectMinimum)
        QtCore.QObject.connect(self.btnTSSearch, QtCore.SIGNAL("clicked()"), MainWindow.doubleEndedConnect)
        QtCore.QObject.connect(self.listTo, QtCore.SIGNAL("currentItemChanged(QListWidgetItem*,QListWidgetItem*)"), MainWindow.selectTransition)
        QtCore.QObject.connect(self.sliderTS, QtCore.SIGNAL("sliderMoved(int)"), MainWindow.showFrameTS)
        QtCore.QObject.connect(self.btnInvert, QtCore.SIGNAL("clicked()"), MainWindow.Invert)
        QtCore.QObject.connect(self.btnConnect, QtCore.SIGNAL("clicked()"), MainWindow.doubleEndedConnect)
        QtCore.QObject.connect(self.btnShowGraph, QtCore.SIGNAL("clicked()"), MainWindow.show_graph)
        QtCore.QObject.connect(self.actionDelete_Minimum, QtCore.SIGNAL("triggered()"), MainWindow.delete_minimum)
        QtCore.QObject.connect(self.btnDisconnectivity_graph, QtCore.SIGNAL("clicked()"), MainWindow.show_disconnectivity_graph)
        QtCore.QObject.connect(self.btnReconnect, QtCore.SIGNAL("clicked()"), MainWindow.doubleEndedReConnect)
        QtCore.QObject.connect(self.actionEditParams, QtCore.SIGNAL("triggered()"), MainWindow.edit_params)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(True)
        self.btnRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BHTab), QtGui.QApplication.translate("MainWindow", "Basin Hopping", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAlign.setText(QtGui.QApplication.translate("MainWindow", "Align", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEnergies.setText(QtGui.QApplication.translate("MainWindow", "Energies", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNEB.setText(QtGui.QApplication.translate("MainWindow", "NEB", None, QtGui.QApplication.UnicodeUTF8))
        self.btnInvert.setText(QtGui.QApplication.translate("MainWindow", "Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDisconnectivity_graph.setText(QtGui.QApplication.translate("MainWindow", "disconnectivity graph", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowGraph.setText(QtGui.QApplication.translate("MainWindow", "show graph", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReconnect.setText(QtGui.QApplication.translate("MainWindow", "Reconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NEBTab), QtGui.QApplication.translate("MainWindow", "NEB", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTSSearch.setText(QtGui.QApplication.translate("MainWindow", "Find TS", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "TS search", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect to Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Minimum.setText(QtGui.QApplication.translate("MainWindow", "Delete Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditParams.setText(QtGui.QApplication.translate("MainWindow", "Edit default parameters", None, QtGui.QApplication.UnicodeUTF8))

from show3d import Show3D
