# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../gui/_blj_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLJSetup(object):
    def setupUi(self, DialogLJSetup):
        DialogLJSetup.setObjectName("DialogLJSetup")
        DialogLJSetup.resize(351, 348)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogLJSetup.sizePolicy().hasHeightForWidth())
        DialogLJSetup.setSizePolicy(sizePolicy)
        DialogLJSetup.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogLJSetup)
        self.buttonBox.setGeometry(QtCore.QRect(30, 280, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(DialogLJSetup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 301, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_sigBB = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_sigBB.setObjectName("lineEdit_sigBB")
        self.gridLayout.addWidget(self.lineEdit_sigBB, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_natoms = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_natoms.setInputMask("")
        self.lineEdit_natoms.setObjectName("lineEdit_natoms")
        self.gridLayout.addWidget(self.lineEdit_natoms, 1, 1, 1, 1)
        self.lineEdit_ntypeA = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ntypeA.setObjectName("lineEdit_ntypeA")
        self.gridLayout.addWidget(self.lineEdit_ntypeA, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_epsAB = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_epsAB.setObjectName("lineEdit_epsAB")
        self.gridLayout.addWidget(self.lineEdit_epsAB, 4, 1, 1, 1)
        self.lineEdit_sigAB = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_sigAB.setObjectName("lineEdit_sigAB")
        self.gridLayout.addWidget(self.lineEdit_sigAB, 3, 1, 1, 1)
        self.lineEdit_epsBB = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_epsBB.setObjectName("lineEdit_epsBB")
        self.gridLayout.addWidget(self.lineEdit_epsBB, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)

        self.retranslateUi(DialogLJSetup)
        self.buttonBox.accepted.connect(DialogLJSetup.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogLJSetup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogLJSetup)

    def retranslateUi(self, DialogLJSetup):
        _translate = QtCore.QCoreApplication.translate
        DialogLJSetup.setWindowTitle(_translate("DialogLJSetup", "Create binary Lennard-Jones system"))
        self.lineEdit_sigBB.setText(_translate("DialogLJSetup", "0.88"))
        self.label_2.setText(_translate("DialogLJSetup", "number type A"))
        self.lineEdit_natoms.setText(_translate("DialogLJSetup", "13"))
        self.lineEdit_ntypeA.setInputMask(_translate("DialogLJSetup", "999; "))
        self.lineEdit_ntypeA.setText(_translate("DialogLJSetup", "10"))
        self.label.setText(_translate("DialogLJSetup", "Number of particles"))
        self.lineEdit_epsAB.setText(_translate("DialogLJSetup", "1.5"))
        self.lineEdit_sigAB.setText(_translate("DialogLJSetup", "0.8"))
        self.lineEdit_epsBB.setText(_translate("DialogLJSetup", "0.5"))
        self.label_3.setText(_translate("DialogLJSetup", "sigma AB"))
        self.label_4.setText(_translate("DialogLJSetup", "eps AB"))
        self.label_5.setText(_translate("DialogLJSetup", "sigma BB"))
        self.label_6.setText(_translate("DialogLJSetup", "eps BB"))
