name: Python Package using Mamba

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      
    - name: create environment with mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        auto-activate-base: false
        activate-environment: pele
        environment-file: environment.yml
    - name: Build + test
      run: |
        pip install --no-build-isolation .[testing]
        nosetests pele
